FROM python:3.10-slim

# Définir le répertoire de travail
WORKDIR /app

# Installer les dépendances
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copier le code source
COPY . .

# Exposer le port pour FastAPI
EXPOSE 8000

# Commande pour démarrer le backend
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
