version: "3.9"

services:

  mysql:
    build:
      context: ./database
      dockerfile: Dockerfile.database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    env_file: .env
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    environment:
      REACT_APP_BACKEND_URL: http://backend:8000
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - mysql
      - backend
    networks:
      - app_network

networks:
  app_network:

volumes:
  mysql_data:
