version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=pokemon_db
    depends_on:
      - mysql
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - mysql
      - backend
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pokemon_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  mysql-data: