version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    env_file: .env
    networks:
      - appnetwork
    depends_on:
      - mysql
  
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - appnetwork
    depends_on:
      - backend
  
  mysql:
    build: ./mysql  
    env_file: .env
    ports:
      - "3306:3306"
    networks:
      - appnetwork
    volumes:
      - mysql-data:/var/lib/mysql


volumes:
  mysql-data:

networks:
  appnetwork: